services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - ./app:/app

    command: >
      sh -c "sleep 15 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database
      - redis

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=taskplatform_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  database_data: