# Generated by Django 5.0.6 on 2024-08-01 10:56

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["id"],
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
        migrations.AlterField(
            model_name="profilefile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=api.models.ProfileFile.get_upload_path,
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="profilefile",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="api.profile",
                verbose_name="Профиль",
            ),
        ),
        migrations.AlterField(
            model_name="profilefile",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время загрузки"
            ),
        ),
    ]
